image:
  repository: tomerdashboardacr12345.azurecr.io/tasks-service
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 2

containerPort: 3002

env:
  - name: PORT
    value: "3002"
  - name: MONGO_URI
    value: "mongodb://admin:adminpass@tasks-service-tasks-service-mongo:27017/tasksdb?authSource=admin"

service:
  type: LoadBalancer
  port: 3002

resources: {}

# --- MongoDB configuration ---
mongo:
  enabled: true
  image: "mongo:7"
  servicePort: 27017

  auth:
    rootUser: admin
    rootPassword: adminpass
    database: tasksdb
    authSource: admin

  persistence:
    enabled: false # enable true in production
    size: 5Gi
    accessModes: ["ReadWriteOnce"]
    storageClassName: "" # specify if you have a storage class

  resources: {} # add CPU/memory limits here if needed
